routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
    ProfileController,
    CompanyController,
    ParamController,
    UserController,
    JobController
};
use App\Models\Job;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function ()
{
    Route::get('/dashboard',function (){
        return view('dashboard');
    })->middleware(['verified']);

    Route::get('/', function () {
        return view('dashboard');
    })->middleware(['verified'])->name('dashboard');

    Route::middleware(['admin'])->group(function ()
    {
        Route::resources([
            'params' => ParamController::class,
        ]);
    });


    Route::resources([
        'users' => UserController::class,
        'jobs' => JobController::class,
    ]);

    Route::get('params/status/{id}', [ParamController::class, "toggleStatus"])->name('params.toggle-status');

    Route::get('job-calender', [JobController::class, 'jobCalender'])->name('jobCalender');
    Route::get('job-logs', [JobController::class, 'jobLogs'])->name('jobLogs');
    Route::get('job-assign-member/{id}', [JobController::class, 'jobAssignMember'])->name('jobAssignMember');
    Route::post('job-assignStore/{id}', [JobController::class, 'jobAssignStore'])->name('jobAssignStore');
    Route::delete('jobs/images/{id}', [JobController::class, 'imageDelete'])->name('jobs.images');
    Route::post('airtable-store', [JobController::class, "airtableStore"])->name('airtableStore');
    Route::get('job-complete', [JobController::class, 'jobComplete'])->name('jobComplete');


    Route::controller(ProfileController::class)->prefix('profile')->name('profile.')->group(function () {
        Route::get('/', 'edit')->name('edit');
        Route::patch('/', 'update')->name('update');
        Route::delete('/', 'destroy')->name('destroy');

        Route::view('/change-password', 'profile.change-password')->name('password');
        Route::post('/change-password', 'changePassword')->name('change-password');
    });
});

require __DIR__.'/auth.php';

app/Models/Params.php
<?php

namespace App\Models;
use App\TraitLibraries\ModelDependentUpload;
use App\TraitLibraries\ModelHelper;
use App\TraitLibraries\ModelSearch;
use Illuminate\Database\Eloquent\Model;


class Params extends Model
{
    public const role = [
        0  =>'all',
        1  =>'admin',
        2  =>'company',
        3  =>'nurse',
    ];

    protected $fillable = [
        'key',
        'type',
        'value',
        'active',
//        'role'
    ];
    protected $guarded  = [];
    use ModelHelper,ModelDependentUpload,ModelSearch;
    //
}

app/Http/Controllers/ParamController.php
<?php

namespace App\Http\Controllers;

use App\Models\Params;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use PhpParser\Builder\Param;

class ParamController extends Controller
{

    protected $_param;

    public function __construct(Params $param)
    {
        $this->_param = $param;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $params = Params::all();
        return view('params.index',compact('params'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = $this->_param;
        return view('params.form',compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'key' => 'required|max:255',
            'value' => 'required',
            'type' => ['required',  Rule::in(['value', 'text'])],
        ]);

        Params::create($request->all());
        return redirect()->route("params.index")->with("success", "Param Created Successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Params  $params
     * @return \Illuminate\Http\Response
     */
    public function show(Params $params)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Params  $params
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Params::findOrFail($id);
        return view('params.form',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Params  $params
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $params = Params::findOrFail($id);
        $params->update($request->all());
        return redirect()->route("params.index")->with("success", "Param Updated Successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Params  $params
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $params = Params::findOrFail($id);
        $params->delete();
        return redirect()->route("params.index")->with("success", "Param Deleted Successfully");
    }

    public function toggleStatus($id)
    {
        $param = Params::findOrFail($id);
        $status = (int) ! (bool) $param->active;
        $param->update(["active" => $status]);
        return redirect()->route("params.index");
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/params/form.blade.php
<x-app-layout>
    <x-slot name="header">
        {{  $model->exists ? __('Edit Param') : __('Create Param')  }}
    </x-slot>

    <div class="row">
        <!-- FormValidation -->
        <div class="col-2"></div>
        <div class="row">
            <!-- FormValidation -->
            <div class="col-2"></div>
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <form id="paramForm" method="post" class="form" action="{{ ($model->exists)? route('params.update', [$model->id]): route('params.store') }}" enctype="multipart/form-data">
                            @if ($model->exists)
                            @method('PUT')
                            @endif
                            @csrf

                             <div class="col-12">
                                <h6 class="fw-semibold">
                                    {{  $model->exists ? __('Edit Param') : __('Create Param')  }}

                                </h6>
                                <hr class="mt-0">
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <div class="fv-plugins-icon-container mb-2">
                                        <label class="form-label" for="form_user_name">Key</label>
                                        <input type="text" id="form_key" value="{{ old('key') ? old('key') : $model->key }}" class="form-control {{ $errors->has('key') ? ' is-invalid' : '' }}" placeholder="Type User Name" name="key">
                                        @if ($errors->has('key'))
                                        <div class="fv-plugins-message-container invalid-feedback">
                                            <div data-field="formValidationBio" data-validator="stringLength">{{ $errors->first('key') }}</div>
                                        </div>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="fv-plugins-icon-container mb-2">
                                        <label class="form-label" for="form_type">Type</label>
                                        <select id="form_type" class="form-control {{ $errors->has('type') ? ' is-invalid' : '' }}" name="type">
                                            <option value="value" {{ (old('type') == 'value' ? 'selected' : $model->type == 'value') ? 'selected' : ''  }}>value</option>
                                            <option value="text" {{ (old('type')  == 'text' ? 'selected' : $model->type == 'text') ? 'selected' : ''  }}>text</option>
                                        </select>
                                        @if ($errors->has('type'))
                                        <div class="fv-plugins-message-container invalid-feedback">
                                            <div data-field="formValidationBio" data-validator="stringLength">{{ $errors->first('type') }}</div>
                                        </div>
                                        @endif
                                    </div>
                                </div>
{{--                                <div class="col-6">--}}
{{--                                    <div class="fv-plugins-icon-container mb-2">--}}
{{--                                        <label class="form-label" for="form_role">Role</label>--}}
{{--                                        <select id="form_role" class="form-control {{ $errors->has('role') ? ' is-invalid' : '' }}" name="role">--}}
{{--                                            @foreach (App\Models\Params::role as $key => $value)--}}
{{--                                                <option value="{{ $key }}" {{ (old('role') ? 'selected' : $model->role == $key) ? 'selected' : ''  }}>{{ $value }}</option>--}}
{{--                                            @endforeach--}}
{{--                                        </select>--}}
{{--                                        @if ($errors->has('role'))--}}
{{--                                        <div class="fv-plugins-message-container invalid-feedback">--}}
{{--                                            <div data-field="formValidationBio" data-validator="stringLength">{{ $errors->first('role') }}</div>--}}
{{--                                        </div>--}}
{{--                                        @endif--}}
{{--                                    </div>--}}
{{--                                </div>--}}
                                <div class="col-12">
                                    <div id="richTextEditorDiv" class="fv-plugins-icon-container mb-2">
                                        <label class="form-label" for="form_user_email">Value</label>
                                        <div id="richTextEditor" style="min-height: 200px;"></div>
                                        @if ($errors->has('value'))
                                        <div class="fv-plugins-message-container invalid-feedback">
                                            <div data-field="formValidationBio" data-validator="stringLength">{{ $errors->first('value') }}</div>
                                        </div>
                                        @endif
                                    </div>
                                    <div id="textAreaDiv" class="fv-plugins-icon-container mb-2">
                                        <label class="form-label" for="form_user_email">Value</label>
                                        <textarea class="form-control {{ $errors->has('key') ? ' is-invalid' : '' }}" name="value" rows="10">@if (old('value')) {{ old('value') }} @elseif($model->value) {{ $model->value }} @endif</textarea>
                                        @if ($errors->has('value'))
                                        <div class="fv-plugins-message-container invalid-feedback">
                                            <div data-field="formValidationBio" data-validator="stringLength">{{ $errors->first('value') }}</div>
                                        </div>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="col-12 mt-3">
                                <button type="submit" name="submitButton" class="btn btn-primary">Submit</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
            <!-- /FormValidation -->
        </div>
        <!-- /FormValidation -->
    </div>
    <x-slot name="scripts">
        <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
        <script>
            var container = document.querySelector('#richTextEditor');
            var quill = new Quill(container, {
                modules: {
                    toolbar: [
                        [{
                            header: [1, 2, false]
                        }],
                        ['bold', 'italic', 'underline'],
                        ['image', 'code-block']
                    ]
                },
                placeholder: 'param value...',
                theme: 'snow' // or 'bubble'
            });

            document.querySelector('#paramForm').addEventListener('submit', (e) => {
                if (document.querySelector('#form_type').value == "text") {
                    document.querySelector('textarea').value = document.querySelector('#richTextEditor > div').innerHTML
                }
            });

            if (document.querySelector('#form_type').value == "value") {
                document.querySelector('#textAreaDiv').style.display = "block"
                document.querySelector('#richTextEditorDiv').style.display = "none"
            } else{
                document.querySelector('#textAreaDiv').style.display = "none"
                document.querySelector('#richTextEditorDiv').style.display = "block"
            }

            document.querySelector('#form_type').addEventListener('change', (e) => {
                if (e.target.value == "value") {
                    document.querySelector('textarea').value = "";
                    document.querySelector('#textAreaDiv').style.display = "block"
                    document.querySelector('#richTextEditorDiv').style.display = "none"
                } else {
                    document.querySelector('#textAreaDiv').style.display = "none"
                    document.querySelector('#richTextEditorDiv').style.display = "block"
                }
            });

        </script>
    </x-slot>

</x-app-layout>

resources/views/params/index.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Manage Params') }}
         <a href="{{ route('params.create') }}" class="btn btn-primary pull-right button-left"><i class="menu-icon tf-icons bx bx-plus"></i> Add New</a>
    </x-slot>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-content">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover mb-0" id="usersTable">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Key</th>
                                    <th>Value</th>
                                    <th>type</th>
                                    <th>role</th>
                                    <th>active</th>
                                    <th>Created At</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($params as $param)
                                    <tr>
                                        <td>{{$param->id ?? '-'}}</td>
                                        <td>{{$param->key ?? '-'}}</td>
                                        <td style="max-width: 250px;">{{ Str::limit($param->value, 110) ?? '-'}}</td>
                                        <td>{{$param->type ?? '-'}}</td>
                                        <td>{{ App\Models\Params::role[$param->role] ?? '-' }}</td>
                                        <td>
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" {{$param->active ? 'checked' : ''}} onclick="window.location.href ='{{ route("params.toggle-status",["id" => $param->id]) }}';">
                                            </div>
                                        </td>
                                        <td>{{$param->created_at ?? '-'}}</td>
                                        <td>
                                            <a href="{{ route('params.edit', $param->id) }}"><i class="tf-icons bx bx-edit"></i></a>


                                            <form style="display: inline" action="{{ route('params.destroy', $param->id)}}"
                                                  id="delete_form_{{$param->id}}" method="post">
                                                @method('DELETE')
                                                @csrf
                                                <a class="badge badge-light delete-confirm-id"
                                                   data-id="{{$param->id}}" title="Delete">
                                                    <i class="tf-icons bx bx-trash text-danger listing_delete_icon"></i></a>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <x-slot name="scripts">
        <script>
            $(function () {
            $("#usersTable").DataTable({
                order: [[0, 'desc']],
            });

        });
        </script>
    </x-slot>
</x-app-layout>