routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
    ProfileController,
    CompanyController,
    ParamController,
    UserController,
    JobController
};
use App\Models\Job;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function ()
{
    Route::get('/dashboard',function (){
        return view('dashboard');
    })->middleware(['verified']);

    Route::get('/', function () {
        return view('dashboard');
    })->middleware(['verified'])->name('dashboard');

    Route::middleware(['admin'])->group(function ()
    {
        Route::resources([
            'params' => ParamController::class,
        ]);
    });


    Route::resources([
        'users' => UserController::class,
        'jobs' => JobController::class,
    ]);

    Route::get('params/status/{id}', [ParamController::class, "toggleStatus"])->name('params.toggle-status');

    Route::get('job-calender', [JobController::class, 'jobCalender'])->name('jobCalender');
    Route::get('job-logs', [JobController::class, 'jobLogs'])->name('jobLogs');
    Route::get('job-assign-member/{id}', [JobController::class, 'jobAssignMember'])->name('jobAssignMember');
    Route::post('job-assignStore/{id}', [JobController::class, 'jobAssignStore'])->name('jobAssignStore');
    Route::delete('jobs/images/{id}', [JobController::class, 'imageDelete'])->name('jobs.images');
    Route::post('airtable-store', [JobController::class, "airtableStore"])->name('airtableStore');
    Route::get('job-complete', [JobController::class, 'jobComplete'])->name('jobComplete');


    Route::controller(ProfileController::class)->prefix('profile')->name('profile.')->group(function () {
        Route::get('/', 'edit')->name('edit');
        Route::patch('/', 'update')->name('update');
        Route::delete('/', 'destroy')->name('destroy');

        Route::view('/change-password', 'profile.change-password')->name('password');
        Route::post('/change-password', 'changePassword')->name('change-password');
    });
});

require __DIR__.'/auth.php';

app/Models/Job.php
<?php

namespace App\Models;

use App\TraitLibraries\ModelDependentUpload;
use App\TraitLibraries\ModelHelper;
use App\TraitLibraries\ModelSearch;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;

class Job extends Model
{
    use HasFactory, ModelHelper, ModelDependentUpload, ModelSearch;
    public static $filepath = "jobs";

    const statuses = [
        self::STATUS_PENDING   => 'pending',
        self::STATUS_ACTIVE    => 'active',
        self::STATUS_CANCEL    => 'cancel',
        self::STATUS_COMPLETE  => 'complete',
        self::STATUS_ASSIGN    => 'assign'
    ];

    const STATUS_PENDING    = 0;
    const STATUS_ACTIVE     = 1;
    const STATUS_CANCEL     = 2;
    const STATUS_COMPLETE   = 3;
    const STATUS_ASSIGN     = 4;


    protected $fillable = [
        'title',
        'date',
        'description',
        'price_doc',
        'job_doc',
        'job_requirement_doc',
        'pickup_doc',
        'estimated_day',
        'price',
        'address',
        'square',
        'longitude',
        'latitude',
        'status',
        'project_detail',

    ];

    public function jobLog()
    {
        return $this->hasOne(JobLog::class, 'job_id', 'id');
    }

    public function scopeStatusPending($query)
    {
        return $query->where('status', 0);
    }

    public function jobDoc()
    {
        return $this->hasMany(File::class, 'objectId', 'id')
            ->where('object','JOBS')->where('type','job_doc');
    }
    public function bannerImages()
    {
        return $this->hasMany(File::class, 'objectId', 'id')
            ->where('object','JOBS')->where('type','banner_image');
    }

    /*
    |--------------------------------------------------------------------------
    | Relations
    |--------------------------------------------------------------------------
    */

    public function user()
    {
        return $this->hasOne(User::class, 'id', 'member_id');
    }


}

app/Http/Controllers/Api/JobController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\CompanyResource;
use App\Http\Resources\JobResource;
use App\Models\Company;
use App\Models\CompleteJob;
use App\Models\Job;
use App\Models\JobLog;
use App\Models\User;
use Carbon\Carbon;
use Dflydev\DotAccessData\Data;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use Mockery\Exception;
use function GuzzleHttp\Promise\all;

class JobController extends BaseController
{
    public function jobListing(Request $request){
        $jobs = Job::with(['jobDoc','bannerImages'])
            ->where('status', JobLog::STATUS_PENDING)->get();
        return $this->sendResult('Job Successfully Fetch.', config('codes.SUCCESS'), new JobResource($jobs), $request);
    }

    public function jobStore(Request $request){
        try {
            $validator = Validator::make($request->all(), [
                'status' => ['required'],
            ]);

            if ($validator->fails()) {
                return $this->sendResult('Validation Error', config('codes.REQUEST_VALIDATAION_ERROR'), $validator->errors()->first(), $request);
            }

            if($request->status == JobLog::STATUS_COMPLETE){
                $job = Job::where('id',$request->job_id)->first();
                $job->status = Job::STATUS_COMPLETE;
                if (!$job->update()) {
                    throw new Exception('Error while saving Job!');
                }
            }

            $jobLog = new JobLog();
            $jobLog->member_id = $request->user()->id;
            $jobLog->job_id = $request->job_id;
            $jobLog->status = JobLog::STATUS_COMPLETE;
            if (!$jobLog->save())
                throw new \Exception('Error saving job');


//            $jobLog = JobLog::where('member_id',$request->user()->id)
//                    ->where('job_id',$request->job_id)->first();
//
//
//            $jobLog->status = $request->status;
//            if (!$jobLog->update()) {
//                throw new Exception('Error while saving JobLog!');
//            }

            return $this->sendResult('Job Successfully Update.', config('codes.SUCCESS'), $job, $request);
        } catch (Exception $e) {
            return $this->sendResult('Job Error.', config('codes.REQUEST_VALIDATAION_ERROR'), ['data' => $e->getMessage()], $request);
        }
    }

//    public function jobStart(Request $request){
//
//        try {
//            $validator = Validator::make($request->all(), [
//                'job_id' => ['required'],
//            ]);
//
//            if ($validator->fails()) {
//                return $this->sendResult('Validation Error', config('codes.REQUEST_VALIDATAION_ERROR'), $validator->errors()->first(), $request);
//            }
//
//            $jobLog = new JobLog();
//            $jobLog->member_id  = $request->user()->id;
//            $jobLog->job_id     = $request->job_id;
//            $jobLog->status     = JobLog::STATUS_START;
//
//            if (!$jobLog->save())
//                throw new \Exception('Error saving job log');
//
//            $job = Job::where('id',$request->job_id)->first();
//            $job->status  = Job::STATUS_ASSIGN;
//            if (!$job->update())
//                throw new \Exception('Error saving job');
//
//            return $this->sendResult('Job Successfully Update.', config('codes.SUCCESS'), $jobLog, $request);
//        } catch (Exception $e) {
//            return $this->sendResult('Job Error.', config('codes.REQUEST_VALIDATAION_ERROR'), ['data' => $e->getMessage()], $request);
//        }
//    }

    public function jobEnd(Request $request){

        try {
            $validator = Validator::make($request->all(), [
                'job_id' => ['required'],
            ]);

            if ($validator->fails()) {
                return $this->sendResult('Validation Error', config('codes.REQUEST_VALIDATAION_ERROR'), $validator->errors()->first(), $request);
            }

            $jobLog = new JobLog();
            $jobLog->member_id  = $request->user()->id;
            $jobLog->job_id     = $request->job_id;
            $jobLog->status     = JobLog::STATUS_ASSIGN;
            if($request->file('e_signature')) $jobLog->e_signature = $jobLog->modelFileUpload($request->file("e_signature"));

            if (!$jobLog->save())
                throw new \Exception('Error saving job');

            $job = Job::where('id',$request->job_id)->first();
            $job->status  = Job::STATUS_ASSIGN;
            if (!$job->update())
                throw new \Exception('Error saving job');

            return $this->sendResult('Job Successfully Update.', config('codes.SUCCESS'), $jobLog, $request);
        } catch (Exception $e) {
            return $this->sendResult('Job Error.', config('codes.REQUEST_VALIDATAION_ERROR'), ['data' => $e->getMessage()], $request);
        }
    }

    public function jobDetail(Request $request,$id){
        $job  = Job::with(['jobDoc','bannerImages'])->where('id',$id)->first();
        return $this->sendResult('Job Successfully View.', config('codes.SUCCESS'), $job, $request);
    }

    public function earnListing(Request $request){
        $jobLogs = JobLog::with(['job.jobDoc','job.bannerImages'])
            ->where('status',JobLog::STATUS_COMPLETE)
            ->where('member_id',$request->user()->id)
            ->get();
        $total = 0;
        foreach ($jobLogs as $jobLog){
            if(!empty($jobLog->job->price)){
                $total += $jobLog->job->price;
            }
        }
        return $this->sendResult('Job Successfully View.', config('codes.SUCCESS'), ['total'=>$total,'jobs'=>$jobLogs], $request);
    }

    public function projects(Request $request){
        $currentDate = Carbon::now()->format('Y-m-d'); // Get the current date in 'YYYY-MM-DD' format
        $currentDateJobs = JobLog::with(['job.jobDoc','job.bannerImages'])
            ->join('jobs', 'jobs.id', '=', 'job_log.job_id')
            ->whereDate('jobs.date', '=', $currentDate)
            ->where('jobs.status', Job::STATUS_ASSIGN)
            ->where('job_log.member_id', $request->user()->id)
            ->get();

        $nextJobs = JobLog::with(['job.jobDoc','job.bannerImages'])
            ->join('jobs', 'jobs.id', '=', 'job_log.job_id')
            ->whereDate('jobs.date', '>', $currentDate)
            ->where('jobs.status', Job::STATUS_ASSIGN)
            ->where('job_log.member_id', $request->user()->id)
            ->get();

        return $this->sendResult('Project Successfully Fetch.', config('codes.SUCCESS'), ['onGoing'=>$currentDateJobs,'upNext'=>$nextJobs], $request);
    }

    public function completeJob(Request $request){

        try {
            $validator = Validator::make($request->all(), [
                'job_log_id'=> ['required'],
                'nails'     => ['required'],
                'dg'        => ['required'],
                'staples'   => ['required'],
            ]);

            if ($validator->fails()) {
                return $this->sendResult('Validation Error', config('codes.REQUEST_VALIDATAION_ERROR'), $validator->errors()->first(), $request);
            }

            $completeJob = new CompleteJob();
            $completeJob->member_id     = $request->user()->id;
            $completeJob->job_log_id    = $request->job_log_id;
            $completeJob->nails         = $request->nails;
            $completeJob->dg            = $request->dg;
            $completeJob->staples       = $request->staples;
            $completeJob->weed_fabric  = $request->weed_fabric;
            $completeJob->glue          = $request->glue;
            $completeJob->seam_type     = $request->seam_type;
            $completeJob->option1       = $request->option1;
            $completeJob->option2       = $request->option2;
            $completeJob->comments      = $request->comments;

            if (!empty($request->photo_seam)) {
                $photo_seam= $completeJob->modelFileUpload($request->file('photo_seam'));
                $completeJob->photo_seam = Job::$filepath.'/'.$photo_seam;
            }

            if (!empty($request->photo_turf)) {
                $photo_turf= $completeJob->modelFileUpload($request->file('photo_turf'));
                $completeJob->photo_turf = Job::$filepath.'/'.$photo_turf;
            }

            if (!$completeJob->save())
                throw new \Exception('Error complete job ');

            $job = Job::where('id',$request->job_id)->first();
            $job->status  = Job::STATUS_COMPLETE;
            if (!$job->update())
                throw new \Exception('Error saving job');

            $job = JobLog::where('id',$request->job_log_id)->first();
            $job->status  = JobLog::STATUS_COMPLETE;
            if (!$job->update())
                throw new \Exception('Error saving job');

            return $this->sendResult('Complete Job Successfully Update.', config('codes.SUCCESS'), $completeJob, $request);
        } catch (Exception $e) {
            return $this->sendResult('Complete Job Error.', config('codes.REQUEST_VALIDATAION_ERROR'), ['data' => $e->getMessage()], $request);
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/jobs/_search.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: warispopal
 * Date: 2/2/19
 * Time: 4:47 PM
 */

?>


    <form class="form validate-form" method="GET" novalidate>
        <div class="form-body">
            <h4 class="form-section"><i class=""></i>Search:</h4>
            <div class="row">
                <div class="col-lg-4 col-md-8">
                    <div class="form-group">
                        <label for="basicInputFile">User Name</label>
                        <div class="position-relative has-icon-left">
                            <input type="text" class="form-control"
                                   name="name"
                                   placeholder="Name"
                                   value="{{ request('name') }}">

                            <div class="form-control-position">
                                <i class="ft-user-check info"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8">
                    <div class="form-group">
                        <label for="basicInputFile">User Email</label>
                        <div class="position-relative has-icon-left">
                            <input type="text" class="form-control"
                                   name="email"
                                   placeholder="Email Address"
                                   value="{{ request('email') }}">
                            <div class="form-control-position">
                                <i class="ft-mail info"></i>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-8">
                    <fieldset class="form-group">
                        <label for="basicSelect">Alpha Roles</label>
                        <select class="form-control" name="alphaRole">
                            <option value="">Select</option>
                            @foreach($alphaRoles as $key => $title)
                                <option value="{{$key}}" {{ ($key == request('alphaRole'))?'selected=""':'' }}>{{$title}}</option>
                            @endForeach
                        </select>
                    </fieldset>
                </div>
                <div class="col-lg-4 col-md-8">
                    <div class="form-group">
                        <label for="basicInputFile">Created</label>
                        <div class="position-relative has-icon-left " id="defaultrange">
                            <input type="text" class="form-control"
                                   name="created_at"
                                   placeholder="Created Date Range"
                                   value="{{ request('created_at') }}">

                            <div class="form-control-position">
                                <i class="ft-clock info"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions right">

            <a href="{{ route('users.index') }}"
               class="btn btn-raised btn-outline-secondary round btn-min-width mr-1 mb-1">Reset</a>
            <button type="submit"
                    class="btn btn-raised btn-outline-success round btn-min-width mr-1 mb-1">
                <i class="fa fa-check-square-o"></i> Search
            </button>
        </div>
    </form>

resources/views/jobs/assignJob.blade.php
<x-app-layout>
    <x-slot name="header">
        Job Assign To Member
    </x-slot>

    <div class="row">
        <!-- FormValidation -->
        <div class="col-2"></div>
        <div class="row">
            <!-- FormValidation -->
            <div class="col-2"></div>
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post" class="form" enctype="multipart/form-data"
                              action="{{route('jobAssignStore', [$model->id])}}">

                            @csrf

                            <div class="col-12">
                                <h6 class="fw-semibold">
                                    Job Assign To Member
                                </h6>
                                <hr class="mt-0">
                            </div>
                            <div class="row">
                                <h3>{{$model->title ?? ''}}</h3>
                                @foreach($members as $member)
                                    <?php
                                        $checked = false;
                                        foreach ($jobLogs as $jobLog){
                                            if($jobLog['member_id'] == $member->id){
                                                $checked = true;
                                                break;
                                            }
                                        };
                                    ?>
                                    <div class="col-2" >
                                        <label class="form-label" for="users">{{$member->first_name.' '.$member->last_name}}</label>
                                        <input type="checkbox" name="users[]" {{($checked)?'checked':''}} value="{{$member->id??''}}">
                                    </div>
                                @endforeach
                                @if ($errors->has('users'))
                                    <div class="fv-plugins-message-container text-danger">
                                        <div data-field="formValidationBio"
                                             data-validator="stringLength" >{{ $errors->first('users') }}</div>
                                    </div>
                                @endif

                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
            <!-- /FormValidation -->
        </div>
        <!-- /FormValidation -->
    </div>

    <x-slot name="scripts">

    </x-slot>

</x-app-layout>

<script>
</script>

resources/views/jobs/calender.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Manage Jobs') }}
        <a href="{{ route('jobs.create') }}" class="btn btn-primary pull-right button-left">
            <i class="menu-icon tf-icons bx bx-plus"></i>Add New
        </a>
    </x-slot>

    <style>
        .fc-title {
            color: white; /* Set the event title color to white */
        }
    </style>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-content">
                    <div class="card-body">
                        <div class="container">
                            <div id="calendar"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <x-slot name="scripts">
        <script src='http://fullcalendar.io/js/fullcalendar-2.1.1/lib/moment.min.js'></script>
        <script src='http://fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery.min.js'></script>
        <script src="http://fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery-ui.custom.min.js"></script>
        <script src='http://fullcalendar.io/js/fullcalendar-2.1.1/fullcalendar.min.js'></script>
        <script>
            $(document).ready(function() {
                $('#calendar').fullCalendar({
                    events: <?php echo $jobs; ?>
                });
            });
        </script>
    </x-slot>
</x-app-layout>

resources/views/jobs/completeJobs.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Job Complete Logs') }}
    </x-slot>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-content">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover mb-0" id="usersTable">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Job</th>
                                    <th>Member</th>
                                    <th>Nails</th>
                                    <th>DG</th>
                                    <th>Staples</th>
                                    <th>Weed Fabric</th>
                                    <th>Glue</th>
                                    <th>Seam Type</th>
                                    <th>Option1</th>
                                    <th>Option2</th>
                                    <th>Comment</th>
                                    <th>Photo Seam</th>
                                    <th>Photo Turf</th>
                                    <th>Created At</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($completeJobs as $completeJob)
                                    <tr>
                                        <td>{{$completeJob->id}}</td>
                                        <td>{{$completeJob->jobLog->job->title ?? ''}}</td>
                                        <td>
                                            <?php
                                            $firstName  = $completeJob->member->first_name ?? '';
                                            $lastName   = $completeJob->member->last_name ?? '';
                                            echo $firstName.' '.$lastName;
                                            ?>
                                        </td>
                                        <td>{{$completeJob->nails}}</td>
                                        <td>{{$completeJob->dg}}</td>
                                        <td>{{$completeJob->staples}}</td>
                                        <td>{{$completeJob->weed_fabric}}</td>
                                        <td>{{$completeJob->glue}}</td>
                                        <td>{{$completeJob->seam_type}}</td>
                                        <td>{{$completeJob->option1}}</td>
                                        <td>{{$completeJob->option2}}</td>
                                        <td>{{$completeJob->comments}}</td>
                                        <td class="text-nowrap">
                                            @if (!empty($completeJob->photo_seam))
                                                <a class="btn btn-sm btn-outline-info" href="{{URL::to('/storage').'/'.$completeJob->photo_seam ?? '#'}}" download=""><i class="tf-icons bx bx-sm bx-cloud-download"></i> Download</a>
                                            @else
                                                <span class="text-muted">N/A</span>
                                            @endif
                                        </td>
                                        <td class="text-nowrap">
                                            @if (!empty($completeJob->photo_turf))
                                                <a class="btn btn-sm btn-outline-info" href="{{URL::to('/storage').'/'.$completeJob->photo_turf ?? '#'}}" download=""><i class="tf-icons bx bx-sm bx-cloud-download"></i> Download</a>
                                            @else
                                                <span class="text-muted">N/A</span>
                                            @endif
                                        </td>
                                        <td class="text-nowrap" title="{{ $completeJob->created_at }}">{{ date("d M, Y", strtotime($completeJob->created_at)) }}</td>
                                        </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <x-slot name="scripts">
        <script>
            $(function () {
                $("#usersTable").DataTable({
                    order: [[0, 'desc']],
                });
            });
        </script>
    </x-slot>
</x-app-layout>

resources/views/jobs/view.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: warispopal
 * Date: 1/12/19
 * Time: 10:04 PM
 */

// user view

?>
<x-app-layout>
    <x-slot name="header">
        {!! $model->name !!}
    </x-slot>
    <div class="row">
        <div class="col-2"></div>
        <!-- Users detail page-->
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">User Details</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>{{$model->id}}</td>
                                    <td>{{$model->name}}</td>
                                    <td>{{$model->email}}</td>
                                    <td>{{$model->created_at}}</td>
                                    <td>{{$model->updated_at}}</td>
                                    <td>
                                        <a href="{{ route('users.edit', $model->id) }}"
                                           class="btn btn-primary">Edit</a>
                                        <form action="{{ route('users.destroy', $model->id)}}" method="post"
                                              style="display: inline-block">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('users.index') }}" class="btn btn-primary">Back</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</x-app-layout>